services:
  db:
    image: postgres
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_USER: animeon
      POSTGRES_PASSWORD_FILE : /run/secrets/db_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "/var/lib/pgdata:/var/lib/postgresql/data/pgdata"
    secrets:
      - db_password
  redis:
    image: redis
    restart: always
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: local:redis:6379
      HTTP_USER: ${REDIS_COMMANDER_USER}
      HTTP_PASSWORD_HASH: ${REDIS_COMMANDER_PASSWORD_HASH}
    ports:
      - "8081:8081"
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "9394:9394"
    environment:
      DATABASE_HOST: db
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default:/etc/nginx/sites-enabled/default:ro
      - ./fullchain.pem:/etc/nginx/fullchain.pem:ro
      - ./privkey.pem:/etc/nginx/privkey.pem:ro
    ports:
      - "443:443"
#      - "8888:80"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus-web-config.yml:/etc/prometheus/web-config.yml:ro
      - prometheusdata:/prometheus
      - ./fullchain.pem:/prometheus/fullchain.pem:ro
      - ./privkey.pem:/prometheus/privkey.pem:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web-config.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}"
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana
      - ./fullchain.pem:/etc/grafana/fullchain.pem:ro
      - ./privkey.pem:/etc/grafana/privkey.pem:ro
      - ./config/grafana.ini:/etc/grafana/grafana.ini
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command:
      - -nginx.scrape-uri=http://web:80/nginx_status
    ports:
      - "9113:9113"
secrets:
  db_password:
    file: ./db_password
volumes:
  grafanadata:
  prometheusdata:
  pgdata:
    driver: local
