global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "animeon"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["metrics.animeon.ru"]
  - job_name: "nginx"
    metrics_path: /metrics
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]
