global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "animeon"
    tls_config:
      - cert_file: /fullchain.pem
      - key_file: /privkey.pem
    metrics_path: /metrics
    static_configs:
      - targets: ["web:443"]
