global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "animeon"
    tls_config:
      cert_file: /prometheus/fullchain.pem
      key_file: /prometheus/privkey.pem
    metrics_path: /metrics
    static_configs:
      - targets: ["https://web:443"]
